#%RAML 1.0 SecurityScheme
type: x-client-enforcement
describedBy:
  headers:
    client_id:
      type: string
      required: true
      example: 93e80db0-a7d4-11ed-afa1-0242ac120002
    client_secret:
       